version: '2'
services:

  mysql-db-bill:
    container_name: billdb
    image: mysql
    # ports:
          # - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: greengo
    volumes:
      - db_data_bill:/var/lib/mysql
      - ${GIT_HOME}/Provider_payment/sql:/docker-entrypoint-initdb.d/
    # all ports available via shared network
    networks:
      - shared

  bill-app:
    container_name: billsrv
    image: billsrvimg
    ports:
          - 8080:8080
    build: 
      context: ${GIT_HOME}/Provider_payment/app
      dockerfile: Dockerfile  
    networks:
      - shared
    volumes:
      - app_data_bill:/in
    entrypoint: 
      - python3 
      - app.py

  mysql-db:
    container_name: mysql-c
    image: mysql
    # ports used for development
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: greengo
    volumes:
      - db_data:/var/lib/mysql
      # this directory is used to automatically load all scripts found in there 
      - ${GIT_HOME}/Weight/mysql/auto-run-scripts:/docker-entrypoint-initdb.d
    # all ports available via shared network
    networks:
      - shared

  weigh-app:
    container_name: weigh-app-c
    image: weigh-app
    ports:
      - "8081:8000"
    environment:
      DB_HOST: mysql-c
    build: 
      context: ${GIT_HOME}/Weight/app
      dockerfile: Dockerfile  
    networks:
      - shared
    volumes:
      - ${GIT_HOME}/Weight/app:/app
      - app_data:/in
    entrypoint: 
      - python3 
      - app.py


volumes:
  app_data_bill:
    driver: local
    driver_opts:
      type: none
      o: bind
      # set based on your environment
      device: "${GIT_HOME}/Provider_payment"

  db_data_bill:
    driver: local
    driver_opts:
      type: none
      o: bind
      # set based on your environment
      device: "${HOME}/billdb"

  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # set based on your environment
      device: "${GIT_HOME}/Weight/app/in"

  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # set based on your environment
      device: "${GIT_HOME}/Weight/mysql/datadir"

networks:
  shared:
    driver: bridge
