#!/bin/sh
set -e

echo "Starting build containers ..."

WORKING_DIR=$1
cd $WORKING_DIR
echo "Working folder is $PWD"
. ./env.ini

echo "Port is $DEVOPS_PORT"

rm -r $LOGS
mkdir $LOGS

#devops_container_name=${DEVOPS_CONTAINER}'-app'
#echo "Devops container is $devops_container_name"
#docker-compose up $devops_container_name 1> $LOGS/out.log 2>$LOGS/errors.log 

#for all services
docker-compose up -d 1> $LOGS/out.log 2>$LOGS/errors.log 


